# Generated by Django 3.1.4 on 2021-01-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210105_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='calorie_content',
            new_name='calories_per_hundred',
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
