# Generated by Django 3.1.4 on 2021-01-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210106_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
