# Generated by Django 3.1.4 on 2021-01-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20210109_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='calorie_content',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calorie_content',
        ),
        migrations.RemoveField(
            model_name='week',
            name='calorie_content',
        ),
    ]
