# Generated by Django 3.1.4 on 2021-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bought_weeks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
